# Generated by Django 5.0.4 on 2024-05-09 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question_generationapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Card',
        ),
        migrations.RemoveField(
            model_name='account',
            name='user_type',
        ),
    ]
