# Generated by Django 5.0.4 on 2024-05-10 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question_generationapp', '0002_delete_card_remove_account_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='user',
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
